title:            GAIA | Sid's Blog
description:      Generally An Information Arsenal
reading_time:     true
words_per_minute: 200


#! Site Domain goes here (https://domain.com) | Leave blank if testing locally, or use http://localhost:4000
url: https://sid200.github.io/blog

#! Owner Info
owner:
  name:           Sid
  avatar:         avatar.png
  bio:            "A random person"
  email:          prollysid@pm.me
  
  #! Socials
  twitter:        prollysid
  github:         sid200
  # linkedin:      
  # instagram:      
  # discord:          
  # google plus id, include the '+', eg +mmistakes
  # google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
# TODO
#  google_analytics: UA-150566975-1
# google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
